{{- $credentials := index .Values.manager "credentials" -}}
{{- if and $credentials.applicationCollection.username $credentials.applicationCollection.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: application-collection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ $credentials.applicationCollection.username | b64enc | quote }}
  token: {{ $credentials.applicationCollection.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: application-collection-auth
  namespace: cattle-system
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ $credentials.applicationCollection.username | b64enc | quote }}
  password: {{ $credentials.applicationCollection.password | b64enc | quote }}
{{- end }}
{{- if and $credentials.nvidia.username $credentials.nvidia.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nvidia-registry 
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ $credentials.nvidia.username | b64enc | quote }}
  token: {{ $credentials.nvidia.password | b64enc | quote }}
{{- end }}
{{- if and $credentials.suseRegistry.username $credentials.suseRegistry.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: suse-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ $credentials.suseRegistry.username | b64enc | quote }}
  token: {{ $credentials.suseRegistry.password | b64enc | quote }}
--- 
apiVersion: v1
kind: Secret
metadata:
  name: suse-ai-registry-auth
  namespace: cattle-system
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ $credentials.suseRegistry.username | b64enc | quote }}
  password: {{ $credentials.suseRegistry.password | b64enc | quote }}
{{- end }}
