{{- $credentials := index .Values.manager "credentials" -}}
apiVersion: ai-platform.suse.com/v1alpha1
kind: Settings
metadata:
  name: settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
spec:
{{- if and $credentials.applicationCollection.username $credentials.applicationCollection.password }}
  applicationCollection:
      tokenSecretRef:
        key: token
        name: application-collection
      userSecretRef:
        key: user
        name: application-collection
{{- end }}
{{- if and $credentials.nvidia.username $credentials.nvidia.password }}
  nvidia:
      tokenSecretRef:
        key: token
        name: nvidia-registry
      userSecretRef:
        key: user
        name: nvidia-registry
{{- end }}
{{- if and $credentials.suseRegistry.username $credentials.suseRegistry.password }}
  suseRegistry:
      tokenSecretRef:
        key: token
        name: suse-registry
      userSecretRef:
        key: user
        name: suse-registry
{{- end }}
